"""init colors

Revision ID: 83f7566b2409
Revises: ccb8843133a6
Create Date: 2024-08-26 08:08:47.525809

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.orm import Session
from app.models import AnswerSetColor, UserQuestionColor


# revision identifiers, used by Alembic.
revision = '83f7566b2409'
down_revision = 'ccb8843133a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    session = Session(bind=bind)

    colors = [
        AnswerSetColor(label='Weiß', value='#FFFFFF'),
        AnswerSetColor(label='Schwarz', value='#000000'),
        AnswerSetColor(label='Rot', value='#FF0000'),
        AnswerSetColor(label='Gelb', value='#FFFF00'),
        AnswerSetColor(label='Grün', value='#00FF00'),
        AnswerSetColor(label='Blau', value='#0000FF'),
        AnswerSetColor(label='Magenta', value='#FF00FF'),
    ]
    
    session.add_all(colors)
    session.commit()
    
    userQuestion = UserQuestionColor(question_text="Wie fühlst du dich heute?")

    colors = session.execute(sa.select(AnswerSetColor)).scalars().all()
    userQuestion.answer_set = colors
    session.add(userQuestion)
    session.commit()
    session.close()
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    session.query(AnswerSetColor).delete()
    session.commit()
    pass
    # ### end Alembic commands ###
