"""init_table_color

Revision ID: 9c917ce84d16
Revises: d5919d28a62a
Create Date: 2024-08-01 08:28:46.716892

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.orm import Session
from app.models import Color


# revision identifiers, used by Alembic.
revision = '9c917ce84d16'
down_revision = 'd5919d28a62a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_color_color'), 'color', ['color'], unique=True)

    bind = op.get_bind()
    session = Session(bind=bind)

    colors = [
        Color(label='Weiß', color='#FFFFFF'),
        Color(label='Schwarz', color='#000000'),
        Color(label='Rot', color='#FF0000'),
        Color(label='Gelb', color='#FFFF00'),
        Color(label='Grün', color='#00FF00'),
        Color(label='Blau', color='#0000FF'),
        Color(label='Magenta', color='#FF00FF'),
    ]
    
    session.add_all(colors)
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_color_color'), table_name='color')
    op.drop_table('color')
    # ### end Alembic commands ###
