"""init_color

Revision ID: d86578ee52c9
Revises: 6497d9a31dc6
Create Date: 2024-08-01 08:09:26.533854

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.orm import Session
from app.models import QuestionType, UserQuestion


# revision identifiers, used by Alembic.
revision = 'd5919d28a62a'
down_revision = 'e78b1e2af183'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    questionType = QuestionType(tech_id="color_picker", label='Farbwähler')
    userQuestion = UserQuestion(question_text="Wie fühlst du dich heute?", question_type=questionType)
    
    session.add(questionType)
    session.add(userQuestion)
    session.commit()
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    session.query(UserQuestion).delete()
    session.query(QuestionType).delete()
    session.commit()
    pass
    # ### end Alembic commands ###