"""init_color

Revision ID: 2069f24e6d98
Revises: 600f6fdd86ae
Create Date: 2024-07-31 09:08:04.225746

"""
from alembic import op
from sqlalchemy.orm import Session
import sqlalchemy as sa
import sqlmodel             # NEW
from app.models import InputType, UserQuestion


# revision identifiers, used by Alembic.
revision = '2069f24e6d98'
down_revision = '600f6fdd86ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    inputType = InputType(tech_id="color_picker", label='Farbwähler')
    userQuestion = UserQuestion(question_text="Wie fühlst du dich heute?", input_type=inputType)
    
    session.add(inputType)
    session.add(userQuestion)
    session.commit()
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    session.query(UserQuestion).delete()
    session.query(InputType).delete()
    session.commit()
    pass
    # ### end Alembic commands ###
