"""fixed unique on user data table

Revision ID: 69545f144293
Revises: 771b84811774
Create Date: 2024-08-29 09:03:51.184973

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '69545f144293'
down_revision = '771b84811774'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_userqdatacolor_value', table_name='userqdatacolor')
    op.create_index(op.f('ix_userqdatacolor_value'), 'userqdatacolor', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userqdatacolor_value'), table_name='userqdatacolor')
    op.create_index('ix_userqdatacolor_value', 'userqdatacolor', ['value'], unique=True)
    # ### end Alembic commands ###
