"""add base data

Revision ID: 76e4a3231c14
Revises: 8084f07a0d05
Create Date: 2024-07-30 11:09:25.840238

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from app.models import InputType


# revision identifiers, used by Alembic.
revision = '76e4a3231c14'
down_revision = '8084f07a0d05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        InputType.__table__.insert().values([
            {'label': 'Farben', 'techId': 'color_picker'}
        ])
    )
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        InputType.__table__.delete().where(
            InputType.__table__.c.techId.in_(['color_picker'])
        )
    )
    pass
    # ### end Alembic commands ###
