"""init colors

Revision ID: 83f7566b2409
Revises: ccb8843133a6
Create Date: 2024-08-26 08:08:47.525809

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.orm import Session
from app.models import Color


# revision identifiers, used by Alembic.
revision = '83f7566b2409'
down_revision = 'ccb8843133a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    session = Session(bind=bind)

    colors = [
        Color(label='Weiß', color='#FFFFFF'),
        Color(label='Schwarz', color='#000000'),
        Color(label='Rot', color='#FF0000'),
        Color(label='Gelb', color='#FFFF00'),
        Color(label='Grün', color='#00FF00'),
        Color(label='Blau', color='#0000FF'),
        Color(label='Magenta', color='#FF00FF'),
    ]
    
    session.add_all(colors)
    session.commit()
    session.close()
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    session.query(Color).delete()
    session.commit()
    pass
    # ### end Alembic commands ###
