"""init

Revision ID: bef2f68e0ec4
Revises: 
Create Date: 2024-08-29 07:59:48.994591

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'bef2f68e0ec4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answersetcolor',
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answersetcolor_value'), 'answersetcolor', ['value'], unique=True)
    op.create_table('userquestioncolor',
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userdatacolor',
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('for_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_question_id'], ['userquestioncolor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userquestioncolorlink',
    sa.Column('user_question_id', sa.Integer(), nullable=False),
    sa.Column('answer_set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_set_id'], ['answersetcolor.id'], ),
    sa.ForeignKeyConstraint(['user_question_id'], ['userquestioncolor.id'], ),
    sa.PrimaryKeyConstraint('user_question_id', 'answer_set_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userquestioncolorlink')
    op.drop_table('userdatacolor')
    op.drop_table('userquestioncolor')
    op.drop_index(op.f('ix_answersetcolor_value'), table_name='answersetcolor')
    op.drop_table('answersetcolor')
    # ### end Alembic commands ###
