"""seed userquestioncolor

Revision ID: db3bde405b72
Revises: 83f7566b2409
Create Date: 2024-08-26 08:11:45.271955

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW
from sqlalchemy.orm import Session
from app.models import Color, UserQuestionColor


# revision identifiers, used by Alembic.
revision = 'db3bde405b72'
down_revision = '83f7566b2409'
branch_labels = None
depends_on = None



def upgrade() -> None:
    bind = op.get_bind()
    session = Session(bind=bind)

    userQuestion = UserQuestionColor(question_text="Wie fühlst du dich heute?")

    colors = session.execute(sa.select(Color)).scalars().all()
    userQuestion.answer_set = colors
    session.add(userQuestion)
    session.commit()
    session.close()

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    session.query(UserQuestionColor).delete()
    session.commit()
    pass
    # ### end Alembic commands ###
