"""init_color

Revision ID: e1dbacf6cb8a
Revises: fe89497a714d
Create Date: 2024-07-31 08:42:52.428739

"""
from alembic import op
from sqlalchemy.orm import Session
import sqlalchemy as sa
import sqlmodel             # NEW
from app.models import InputType, UserQuestion


# revision identifiers, used by Alembic.
revision = 'e1dbacf6cb8a'
down_revision = 'fe89497a714d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    inputType = InputType(tech_id="color_picker", label='Farbwähler')
    userQuestion = UserQuestion(question_text="Wie fühlst du dich heute?", input_type=inputType)
    
    session.add(inputType)
    session.add(userQuestion)
    session.commit()
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    session.query(UserQuestion).delete()
    session.query(InputType).delete()
    session.commit()
    pass
    # ### end Alembic commands ###
